export enum EstadoCompra {
    PAGADO = 'PAGADO',
    PENDIENTE = 'PENDIENTE',
    CANCELADO = 'CANCELADO',
    REEMBOLSADO = 'REEMBOLSADO',
    ENTREGADO = 'ENTREGADO',
    ENVIADO = 'ENVIADO',
    
}